### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by diegofaundezm** [ofou/fisica#113]
hola bro, como puedo actualizar el repositorio? he tratado como me dicen mis compañeros y no he podido

**Comment by ofou** [comment]
¿Puedes copiar el código del error?

**Comment by diegofaundezm** [comment]
es que ni siquiera me da un error, mis compañeros me dijeron que tenia que
irme a VCS luego a git, pull, y ahi en retome deberia aparecerme un link,
pero no me sale

**Comment by diegofaundezm** [comment]
es que ni siquiera me da un error, mis compañeros me dijeron que tenia que
irme a VCS luego a git, pull, y ahi en retome deberia aparecerme un link,
pero no me sale

**Comment by ofou** [comment]
Por lo que he visto en tu repositorio, lo tienes desactualizado. Tienes que primero actualizar y luego hacer un branch nuevo y desde ahí, hacer los commits que contengan los cambios pedidos por grupo. 

Para actualizar asegúrate que el remote esté bien configurado en VCS.
