### ISSUE TITLE
Ayuda animacion

### ISSUE THREAD

**Issue by LeviiU** [ofou/fisica#123]
no entiendo bien como modificar el codigo de ejemplo animado para mi curva, podrias ayudarme?

**Comment by ofou** [comment]
Hola @LeviiU aquí tienes un [ejemplo](https://matplotlib.org/2.1.2/gallery/animation/simple_3danim.html) y [otro](https://matplotlib.org/2.1.2/gallery/mplot3d/wire3d_animation.html#sphx-glr-gallery-mplot3d-wire3d-animation-py) y [otro](https://matplotlib.org/2.1.2/gallery/animation/double_pendulum_animated_sgskip.html#sphx-glr-gallery-animation-double-pendulum-animated-sgskip-py) ejemplo de cómo se anima la curva
