### ISSUE TITLE
Tarea Evaluada 2: Animaciones en 3D (15%)

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#128]
En esta segunda tarea evaluada los grupos ya designados con sus presentes curvas deberán cumplir una serie de requisitos los cuales tienen una ponderación de 1.0 puntos cada uno con un punto base, el grupo que cumpla con todos los puntos será evaluado con nota 7.0. Recuerden que esta entrega tiene una ponderación de un 15% con respecto a la entrega final del software colaborativo. En esta penúltima entrega haremos enfasis en resolver problemas de requisitos _específicos_ y además en la parte _colaborativa_, la solución de sus problemas respectivos deberán añadirlos al archivo añadido en el commit https://github.com/ofou/fisica/commit/6843f98d897e8b23ed0e508ee11af5c05868e32a. Los requisitos son los siguientes:

- [ ] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [ ] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana. 
- [ ] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva [en 45°](https://github.com/matplotlib/matplotlib/issues/1077#issuecomment-14006279)
- [ ] Abrir un issue con el nombre de su curva, la presente [todo list](https://help.github.com/en/articles/about-task-lists) con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [ ] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [ ] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

Es posible enviar esta entrega hasta el día domingo 9 de Junio, a las 23:59. Los grupos que envíen más tarde serán evaluados con nota mínima por orden del profesor en esta presente entrega. Cualquier duda que tengan con esta entrega no duden en comentar en este issue. 

Adjunto los grupos:

Curva seleccionada | Grupo | Nota
-- | -- | --
Hélice Conica | Mario Labbé (@LsMario1998) <br />Mario González (@tatameister)<br />Cristóbal Cortés (@cristobal140)<br />Thadly Guerra (@Thadly64)<br />Luis Inostroza (@luisinostrozaf)<br /> |  
Hélice Circular | Felipe Lopez Vergara (@felipelopez00)<br />Bastian Bustamante Moraga (@BastianBustamante)<br />Rodrigo Torrez Queupan (@imperium31)<br />Juan Hernandez Gatica (@juanpablo1994)<br />Eric Rojas Palma (@valukar)<br /> |  
Corona Sinusoidal | Luis Soto Zelada (@Luiss23)<br />Diego Rojas (@diegoskky)<br />Lucia Vilches (@luciavj)<br /> |  
Curva de Viviani | Levi Urbina (@LeviiU)<br /> Natalia Valenzuela (@NatyVV)<br /> Ricardo Vergara(@ricardovergarat)<br /> Estefany Alarcon(@estefanyai)<br /> |  
Hipopoda | Boris Gutiérrez Cornejo (@BorisAndresLmb)<br />Juan González Jélvez (@JuanGonzalez33)<br />Pablo Barrera Whiteley (@Pablobw)<br />José Flores Cáceres (@JoseFlores9)<br />Cristobal Rojas Saavedra (@cristotix)<br /> |  
Espiral Cónica de Papus | José Fabián Ignacio González Encina (@GoldenFenix)<br />Cristian Eduardo Castillo (@criseduardjjd)<br />Diego Faundez Mendez(@diegofaundezm)<br />Claudio Alcaino Muñoz (@klauser99)<br />Francisco Castillo Moraga(@taifokk)<br /> |  
Curva de Arquitas | Nicolas Fernandez (@matiche)<br />Sebastian Mendez  (@SebaMendez)<br />Cristobal Moreira (@cmoreirab)<br />Gabriel Lara  (@Gabolara453)<br />Dennis Queirolo   (@dennis-queirolo)<br /> |  
Horóptera | Dennys Moraga(@tiodona)<br />Isai Morales (@tioisai)<br />Cristopher Moreno (@Anon0101001)<br />Jose Martinez (@JoseIMG)<br /> |  
Curva Bicilindrica | Nicolas Pavez Henriquez(@nicoopavez)<br />Fracisco Gonzales Vidal(@panchoska8)<br />Greis Quezada (@matakuri)<br />Pedro Robles Fuentes (@PedroRobles)<br /> |  

👩‍💻 Happy coding! 👨‍💻

**Comment by LeviiU** [comment]
Cuando hay que comentar la curva de otro compañero de que manera hay que hacerlo? debemos poner nuestro nombre y un comentario para colaborar a su codigo o algo asi? no entendi bien ese punto

**Comment by ofou** [comment]
@LeviiU Quiere decir que tiene que cada unos de los compañeros del equipo (logueado con su cuenta)  debe ir a algún Issue/pull request de otro equipo y comentar algo que _aporte_ al código de los compañeros.

**Comment by ofou** [comment]
Apropósito @LeviiU necesito los nombres de Github para los demás de tu team. 

- Levi Urbina (@LeviiU)
- Natalia Valenzuela
- Ricardo Vergara
- Estefany Alarcon

**Comment by LeviiU** [comment]
aqui los dejo y gracias por la respuesta
> * Levi Urbina (@LeviiU)
> * Natalia Valenzuela (@NatyVV)
> * Ricardo Vergara(@ricardovergarat)
> * Estefany Alarcon(@estefanyai)

**Comment by LeviiU** [comment]
Por cierto otra duda que tengo es sobre este punto:
Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
que hay que describir exactamente? lo que hace el codigo?

**Comment by ofou** [comment]
> que hay que describir exactamente? lo que hace el codigo?

Exacto.

**Comment by BorisAndresLmb** [comment]
Hola, cuando se refiere a duración de 5 segundos ¿Es máximo 5 segundos? o tiene que ser exactamente 5s

**Comment by juangonzalez33** [comment]
Con respecto a los fps , ¿hay alguna linea de codigo para saber a cuantos fps esta corriendo la animacion?

**Comment by JoseFlores9** [comment]
Con respecto al punto 3, la imagen que va en el botón debe subirse también?

**Comment by ofou** [comment]
> Hola, cuando se refiere a duración de 5 segundos ¿Es máximo 5 segundos? o tiene que ser exactamente 5s

Idealmente @BorisAndresLmb pero no es extricto, con que se tarde apróximadamente 5seg está bien.

**Comment by ofou** [comment]
> Con respecto a los fps , ¿hay alguna linea de codigo para saber a cuantos fps esta corriendo la animacion?

Depende de la implementación, pero [acá](https://stackoverflow.com/questions/26202164/funcanimation-goes-past-the-frames-argument) hay algunas ideas.

**Comment by ofou** [comment]
> Con respecto al punto 3, la imagen que va en el botón debe subirse también?

Así es, este es uno de los puntos a cumplir en la _todo_ list.

**Comment by ofou** [comment]
> En esta segunda tarea evaluada los grupos ya designados con sus presentes curvas deberán cumplir una serie de requisitos los cuales tienen una ponderación de 1.0 puntos cada uno con un punto base, el grupo que cumpla con todos los puntos será evaluado con nota 7.0. Recuerden que esta entrega tiene una ponderación de un 15% con respecto a la entrega final del software colaborativo. En esta penúltima entrega haremos enfasis en resolver problemas de requisitos _específicos_ y además en la parte _colaborativa_, la solución de sus problemas respectivos deberán añadirlos al archivo añadido en el commit [6843f98](https://github.com/ofou/fisica/commit/6843f98d897e8b23ed0e508ee11af5c05868e32a). Los requisitos son los siguientes:
> 
> * [ ]  Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
> * [ ]  Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
> * [ ]  Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva [en 45°](https://github.com/matplotlib/matplotlib/issues/1077#issuecomment-14006279)
> * [ ]  Abrir un issue con el nombre de su curva, la presente [todo list](https://help.github.com/en/articles/about-task-lists) con los puntos marcados y describir el proceso de animación (min. 4 lineas)
> * [ ]  Abrir la pull request y referenciar el issue que abrieron anteriormente
> * [ ]  Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.
> 
> Es posible enviar esta entrega hasta el día domingo 9 de Junio, a las 23:59. Los grupos que envíen más tarde serán evaluados con nota mínima por orden del profesor en esta presente entrega. Cualquier duda que tengan con esta entrega no duden en comentar en este issue.
> 
> Adjunto los grupos:
> 
> Curva seleccionada	Grupo	Nota
> Hélice Conica	Mario Labbé (@LsMario1998) 
> Mario González (@tatameister)
> Cristóbal Cortés (@cristobal140)
> Thadly Guerra (@Thadly64)
> Luis Inostroza (@luisinostrozaf)
>  
> Hélice Circular	Felipe Lopez Vergara (@felipelopez00)
> Bastian Bustamante Moraga (@BastianBustamante)
> Rodrigo Torrez Queupan (@imperium31)
> Juan Hernandez Gatica (@juanpablo1994)
> Eric Rojas Palma (@Valukar)
>  
> Corona Sinusoidal	Luis Soto Zelada (@Luiss23)
> Diego Rojas (@diegoskky)
> Lucia Vilches (@luciavj)
>  
> Curva de Viviani	Levi Urbina (@LeviiU)
> Natalia Valenzuela (@NatyVV)
> Ricardo Vergara(@ricardovergarat)
> Estefany Alarcon(@estefanyai)
>  
> Hipopoda	Boris Gutiérrez Cornejo (@BorisAndresLmb)
> Juan González Jélvez (@juangonzalez33)
> Pablo Barrera Whiteley (@Pablobw)
> José Flores Cáceres (@JoseFlores9)
> Cristobal Rojas Saavedra (@cristotix)
>  
> Espiral Cónica de Papus	José Fabián Ignacio González Encina (@GoldenFenix)
> Cristian Eduardo Castillo (@criseduardjjd)
> Diego Faundez Mendez(@diegofaundezm)
> Claudio Alcaino Muñoz (@klauser99)
> Francisco Castillo Moraga(@taifokk)
>  
> Curva de Arquitas	Nicolas Fernandez (@matiche)
> Sebastian Mendez (@SebaMendez)
> Cristobal Moreira (@cmoreirab)
> Gabriel Lara (@Gabolara453)
> Dennis Queirolo (@dennis-queirolo)
>  
> Horóptera	Dennys Moraga(@tiodona)
> Isai Morales (@tioisai)
> Cristopher Moreno (@Anon0101001)
> Jose Martinez (@JoseIMG)
>  
> Curva Bicilindrica	Nicolas Pavez Henriquez(@nicoopavez)
> Fracisco Gonzales Vidal(@panchoska8)
> Greis Quezada (@matakuri)
> Pedro Robles Fuentes (@PedroRobles)
>  
> 👩‍💻 Happy coding! 👨‍💻

Chicos a todo esto no veo ni _issues_ ni muchas _pull request_ abiertas, recuerden que es un punto por cada elemento de la lista de tareas a cumplir.

**Comment by LeviiU** [comment]
Tengo una duda respecto a este punto:
Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)

donde dice la presente todo list con los puntos marcados, debemos marcar los puntos que cumpla nuestro codigo o que hay que hacer ahi?

**Comment by ofou** [comment]
Hola @LeviiU, ésta es la lista a la que me refiero, puedes marcar los items que tu grupo y tu hayan completado satisfactoriamente con una `x` de esta manera `- [x] texto...`.

`- [ ] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [ ] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana. 
- [ ] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva [en 45°](https://github.com/matplotlib/matplotlib/issues/1077#issuecomment-14006279)
- [ ] Abrir un issue con el nombre de su curva, la presente [todo list](https://help.github.com/en/articles/about-task-lists) con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [ ] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [ ] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.` 

y si te fijas en la parte superior existe un botón que dice __new__ y se refiere a los issues. O siguiendo el link `https://github.com/ofou/fisica/issues/new`.

**Comment by JoseIMG** [comment]
no logro entender lo de los fps no se si es lo de colocar en funcAnimation frames = 60 o es otra cosa

**Comment by Pablobw** [comment]
> no logro entender lo de los fps no se si es lo de colocar en funcAnimation frames = 60 o es otra cosa

Los fps van ligados con el argumento interval, el cual es el delay entre cada cuadro en mili segundos, como consejo podrían dejar el valor de interval en 16 o 17 y los frames pueden dejar un valor entre 80 y 100

**Comment by JoseIMG** [comment]
ayuda se puede eleminar commits desde la pull request que se me agregaron cosas de la tarea 1???

**Comment by ofou** [comment]
Si se pueden eliminar, solo tienes que usar el comando git rm

**Comment by ofou** [comment]
Estoy orgulloso de todos los que comentaron los códigos de sus compañeros. 👏👏👏

Eso sí, aún veo algunos _fix_ en pull requests sin # después 👀. Recuerden que es _fix numerodeissue_ y __en__ el título de la pull. Tienen hasta las 6am sin penalización todos para que arreglen estos pequeños detalles.

Happy coding! 🤖

**Comment by ofou** [comment]
Chicos, ya están las notas publicadas en #129. 
¡Nos vemos el jueves!
