### ISSUE TITLE
Curva Hipopoda

### ISSUE THREAD

**Issue by BorisAndresLmb** [ofou/fisica#135]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
- [x] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°
- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

Proceso de animación:
Para generar la animación, se crearon dos funciones:
1.- Gen: Función que no recibe argumentos, su función es, inicializar los datos y generar arreglos de la función desde el límite entregado menor hasta el límite entregado superior, todo esto para luego entregarlos  a la función update.
2.-Update: La función recibe como argumento, el num, que significa el número de veces que se ejecutará el programa, comienza de 0 hasta 100, data, que es el dato que retorna la función gen. y por último line, que refiere a la creación y actualización de el gráfico en vivo.
Para la animación se ejecute, se utiliza la función Animation que recibe como argumento:
fig: tipo de figura
update: función que actualiza la animación
N(Frames): Veces que se ejecuta la animación
Interval:Delay entre cuadros en milisegundos.  Con esto se va generando el gráfico con 17 milisegundos de delay entre cada cuadro, el equivalente a 60 fps.
blit=False: el blitting no se ejecuta
repeat: Permite que la animación se repita o no, con True o False.

**Comment by taifokk** [comment]
en  la linea anim = ani.FuncAnimation(fig, update, N, fargs=(data, line), interval=1700 / N,repeat=False) pueden cambiar el interval=1700/N por un 17 el cual cumple la misma función y es más simple

**Comment by JoseIMG** [comment]
si hacian las variables xyz podian acortar varias lineas de codigo.
se podia crear el array facilmente
data = [x,y,z]
y luego data = np.array(data)

**Comment by ofou** [comment]
Boris Gutiérrez Cornejo (@BorisAndresLmb)<br />
Juan González Jélvez (@JuanGonzalez33)<br />
Pablo Barrera Whiteley (@Pablobw)<br />
José Flores Cáceres (@JoseFlores9)<br />
Cristobal Rojas Saavedra (@cristotix)<br />

6/6 Well done!
