### ISSUE TITLE
Curva de Viviani 

### ISSUE THREAD

**Issue by LeviiU** [ofou/fisica#136]
- [x]  Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x]  Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
- [x]  Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°
- [x]  Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [x]  Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x]  Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

Primero creamos la figura y establecemos que es de tipo 3D, tras esto establecemos el titulo del grafico y los limites que tendran sus ejes, tras esto, si establecemos los valores de nuestra variable T que vendria siendo el angulo que va adaptando cada punto de la curva, establecemos la ecuacion de cada variable, introducimos los ejes en una lista, y esta lista en un array para poder crear la linea con FuncAnimation.

**Comment by diegoskky** [comment]
Tal vez para que la animación tenga una tasa de 60 FPS deberían revisar la función 'animation.FuncAnimation()' dentro de esta función establecer los FPS que se requieren y asi poder arreglar ese punto

**Comment by juangonzalez33** [comment]
Su pull request tiene muchos archivos cambiados que crean conflictos , por ejemplo borraron el archivo demo.
Intenten revertir los cambios a los archivos que no sean tarea02

**Comment by BorisAndresLmb** [comment]
Me parece que los 60 fps están bien, ya que pusieron interval = 16 , lo que significa que cada 16 milisegundos se actualiza un nuevo frame, lo que equivale a 60 fps

**Comment by Valukar** [comment]
No sé si lo consideraron, pero en la linea 48:
`linea, = grafico.plot(ejes[0, 0:1], ejes[1, 0:1], ejes[2, 0:1], 'm', label="Curva de Viviani", lw=5)`

Si quieren que aparezca el label, podrían escribir `grafico.legend()` en una nueva linea debajo.

**Comment by juanpablo1994** [comment]
Una de las diferencias con nuestro código (hélice circular) es en la parte de: 

 imagen_viviani =  PhotoImage(file="Viviani_curve.png")
    viviani = Button(master=frame,image=imagen_viviani,width=100,height=100,command=curva_de_viviani)
    viviani.pack()
en donde nosotros decidimos cambiar la imagen a formato .gif par trabajar mejor con tkinter puesto que los mejores formatos para trabajar imágenes en tkinter son . gif, .pgm o .ppm.
también nosotros recortamos la imagen de manera externa a 100x100 para así no hacerlo en el código

**Comment by Thadly64** [comment]
Veo que pusieron interval = 16 para poder llevar a cabo los 60 fps a plenitud, algo q a mi grupo le costó un poco, por lo demas todo bien, me gustó la forma en la que reemplazaron su función dentro del código, bastante optima.

**Comment by ofou** [comment]
6/6 Well done guys! 

"Levi Urbina (@LeviiU)
Natalia Valenzuela (@NatyVV)
Ricardo Vergara(@ricardovergarat)
Estefany Alarcon(@estefanyai)
