### ISSUE TITLE
Curva Hélice Circular

### ISSUE THREAD

**Issue by Valukar** [ofou/fisica#138]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración.
- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
- [x] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°.
- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas).
- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente.
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

Descripcion: 

Ocupando las bibliotecas numpy y matplotlib creamos dos funciones: gen y update.
Con estas dos funciones generamos los valores iniciales y los parámetros con los que se generará la curva para luego ir reemplazando las correspondientes variables de nuestra ecuacion de la curva. Al tener esto, podemos animarla utilizando una función presente en matplotlib (FuncAnimation), que recibe como argumentos, fig, que es el tipo de figura; update, que es la función que utilizamos para actualizar la animación; N, las veces que se ejecuta la animación; interval, el retraso entre cada cuadro medida en milisegundos; repeat, que especifica si la animación se repite o no.

**Comment by cristotix** [comment]
En la linea 46 tienen un valor que se llama -0.0
creo que el 0.0 no es  necesario colocarle signo
ya que es neutral

**Comment by JoseFlores9** [comment]
en la linea "ani = animation.FuncAnimation(fig, update, N, fargs=(data, line), interval=16, blit=False, repeat=False)" se puede obviar el argumento blit=False, dado que por defecto es False.

**Comment by ofou** [comment]
Felipe Lopez Vergara (@felipelopez00)
Bastian Bustamante Moraga (@BastianBustamante)
Rodrigo Torrez Queupan (@imperium31)
Juan Hernandez Gatica (@juanpablo1994)
Eric Rojas Palma (@valukar)

Efectivamente 6/6 por ende tienen nota 7.0 en esta tarea.
closes #138 #141

**Comment by ofou** [comment]
#141
