### ISSUE TITLE
Curva Hélice Cónica

### ISSUE THREAD

**Issue by tatameister** [ofou/fisica#139]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración

- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.

- [x] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°

- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)

- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente

- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

Para realizar la animación de esta curva, utilizamos funciones de la biblioteca animation de matplotlib, pero antes de implementarlas creamos una función llamada gen y update, que sirven para generar arreglos de las coordenadas y actualizar el gráfico respectivamente, luego creamos el sistema referencial y enlazamos los datos obtenidos para obtener la gráfica.
Luego, para las interfaces, creamos una ventana con la biblioteca tkinter y 2 botones, que tienen como función desplegar la curva al clickearlos, para insertar la imagen en uno de ellos utilizamos el comando tk.PhotoImage("y la imagen en formato gif") y con el comando "command" enlazamos el botón a la función que despliega la curva.

**Comment by BorisAndresLmb** [comment]
Ojo con los archivos que agregaron de más en el pull request, reviertan esos cambios y solo cambien tarea02.py

**Comment by BorisAndresLmb** [comment]
> Ojo con los archivos que agregaron de más en el pull request, reviertan esos cambios y solo cambien tarea02.py

Pueden borrarlos directamente desde el github, o usando el comando "git rm en pycharm"

**Comment by estefanyai** [comment]
En la linea 52 de su código "ani = animation.FuncAnimation(fig, update, N, fargs=(data, line), interval=1000 / N, blit=False, repeat=False)", en la parte de interval colocan 1000/N siendo N=150. Esto hace que el código se reproduzca a 6.666.. segundos, en el que deberían ser 5

**Comment by estefanyai** [comment]
Si cambian el interval a 16 se supone que les queda en 5

**Comment by criseduardjjd** [comment]
importaron algunas bibliotecas 2 veces creo que es algo innecesario

**Comment by GoldenFenix** [comment]
Hay algunos archivos que están demás dentro del pull, podrían corregir eso y tomar en cuenta los demas issues.

**Comment by ofou** [comment]
Mario Labbé (@LsMario1998) <br />
Mario González (@tatameister)<br />
Cristóbal Cortés (@cristobal140)<br />
Thadly Guerra (@Thadly64)<br />
Luis Inostroza (@luisinostrozaf)<br />

`6/6 == 7.0 True`
