### ISSUE TITLE
Curva Horóptera (En Proceso)

### ISSUE THREAD

**Issue by JoseIMG** [ofou/fisica#142]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
- [x] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°
- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.
Descripcion animacion:
En la función se crean las variables para el gráfico, luego las variables de las formulas parametricas x,y,x mas las del radio r ,una constante c y t que da el espacio de posiciones .Luego se hace un arreglo con x,y,z  que al final se pasa a la funcAnimation que recibe la lista de posiciones x,y,z y pasa por todas las posiciones y las dibuja en la grafica

**Comment by LsMario1998** [comment]
En la linea 54 de su codigo donde se le entregan los argumentos a las funcion FuncAnimation no es necesario colocar el argumento blit=False ya que por defecto tiene este valor, ademas como sugerencia trabajar la imagen como gif ya que tiene mayor compatibilidad con tkinter

**Comment by felipelopez00** [comment]
En la linea 68 de tú codigo se recomienda que ocupen formato gif en la imagen que importes, ya que anda mejor en la biblioteca Tkinter

**Comment by luciavj** [comment]
como recomendación usar la imagen en formato gif debido a que es mayor afinidad con Tkinter

**Comment by tioisai** [comment]
como dijo la compañera luciavj el formato gif queda mejor con Tkinter aparte en algunos pc no toma correctamente la imagen

**Comment by ofou** [comment]
6/6 (7.0) Well done!

Dennys Moraga(@tiodona)
Isai Morales (@tioisai)
Cristopher Moreno (@Anon0101001)
Jose Martinez (@JoseIMG)
