### ISSUE TITLE
Corona Sinusoidal (Proceso Terminado)

### ISSUE THREAD

**Issue by Luiss23** [ofou/fisica#145]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana. 
- [x] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva [en 45°]
- [x] Abrir un issue con el nombre de su curva, la presente [todo list](https://help.github.com/en/articles/about-task-lists) con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

_Originally posted by @ofou in https://github.com/ofou/fisica/pull/132#issuecomment-499125335_

_Proceso de animación:

Se utiliza matplotlib para crear una animación, en este caso de una Corona Sinusoidal. Se hace esto con la 'clase' matplotlib.animation. Esta última se asocia a la 'FuncAnimation' de Matplotlib para poder crear un bucle de animación, pero hacemos que esta no se repita gracias al parámetro de Repeat=False que le agregamos a dicha función, esto para tratar de que la animación sólo dure los cinco segundos, y no se vuelva a ejecutar el gráfico nuevamente.

**Comment by imperium31** [comment]
recuerda crear la pull request, ya que no sale en las pull actuales y no enviarlos con archivos basura

**Comment by matakuri** [comment]
También recuerden utilizar formato gif que anda mejor con tkinter

**Comment by ofou** [comment]
6/6  (7.0) pero para la entrega final no pueden añadir a la pull request archivos innecesarios como los que fueron borrados en el commit https://github.com/ofou/fisica/pull/152/commits/ab63ba9ae931a21c66102fac5a25a9963656f461

Well done!

**Comment by ofou** [comment]
3/6  (4.0) No me aparecen las curvas tridimensionales al menos en el último commit 6b2c9b80a6363d0a5b2b900e76f5d4b5047b99b1 y también tuve que borrar archivos con conflictos https://github.com/ofou/fisica/pull/152/commits/ab63ba9ae931a21c66102fac5a25a9963656f461
