### ISSUE TITLE
Curva Bicilindrica

### ISSUE THREAD

**Issue by nicoopavez** [ofou/fisica#148]
- [ ] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x]  Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
 - [ ] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°
- [ ]  Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
 - [x] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

**Comment by luisinostrozaf** [comment]
Revisar comentarios del pull request, e intentar corregir los errores mencionados, saludos.

**Comment by ofou** [comment]
Chicos no pude hacer ejecutar el código correctamente y tampoco adjuntaron la imagen para el botón.

3/6 (4.0)

**Comment by ofou** [comment]
Los  detalles de sus errores están acá... https://github.com/ofou/fisica/pull/143/files
