### ISSUE TITLE
conica de papus

### ISSUE THREAD

**Issue by criseduardjjd** [ofou/fisica#149]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
- [x] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°
- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.
ocupamos 2 bibliotecas matplotlib y numpy para poder crear la funcion, luego se usa matplotlib.animation para la animacion de la funcion, generamos los valores iniciales y los parámetros con los que se generará la curva para luego ir reemplazando las correspondientes variables de nuestra ecuacion de la curva, esta funcion tiene la figura como de un reloj de arena

**Comment by Luiss23** [comment]
Recuerden utilizar el contabilizado de tareas pendientes o realizadas además de la descripción del issue.

**Comment by Anon0101001** [comment]
creando las variables para los ejes xyz podían hacer un array sin tener que usar la funcion gen.

**Comment by ofou** [comment]
5/6 = 6.0 Añadan el archivo del botón

- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración
- [x] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.
- [ ] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°
- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)
- [x] Abrir la pull request y referenciar el issue que abrieron anteriormente
- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas
