### ISSUE TITLE
Curva de Arquitas

### ISSUE THREAD

**Issue by cmoreirab** [ofou/fisica#155]
- [x] Animar la curva de inicio a fin con una tasa de refresco de 60FPS y 5seg. de duración

- [ ] Añadir un evento al click del botón y enlazar la función de despliega la curva en la nueva ventana.

- [ ] Añadir una imagen al botón de tamaño 100x100px con una captura estática de la curva en 45°

- [x] Abrir un issue con el nombre de su curva, la presente todo list con los puntos marcados y describir el proceso de animación (min. 4 lineas)

- [ ] Abrir la pull request y referenciar el issue que abrieron anteriormente

- [x] Comentar al menos una vez por integrante el issue de un compañero referenciando código e ideas de implementación, sugerencias o diferencias con su código.

Se ocuparon las bibliotecas numpy y matplotlib, ocupando de esta ultima la sublibreria axes3d y la sublibreria animation. Con el uso de estas bibliotecas se crearon las funciones  gen y gen1. Estas funciones crean un parámetro con el cual permite crear una figura mediante la función plt. Estos parámetros son ejes de un plano en tercera dimensión el cual finalmente gráfica una doble curva con un cruce en el eje (0,0,0). 
El programa finalmente grafica ambas curvas en 3D dándole run.

**Comment by ofou** [comment]
3/6 (4.0) no adjuntaron la imagen para el botón y tampoco lograron encapsular correctamente la función. 

Nicolas Fernandez (@matiche)
Sebastian Mendez  (@SebaMendez)
Cristobal Moreira (@cmoreirab)
Gabriel Lara  (@Gabolara453)
Dennis Queirolo   (@dennis-queirolo)
