### ISSUE TITLE
Problema 

### ISSUE THREAD

**Issue by FernandoSO** [ofou/fisica#21]
Siguiendo los pasos del video, al momento de agregar el nombre en el archivo lista, solo aparece un nombre.... no el resto de los compañeros

**Comment by ofou** [comment]
Hola @FernandoSO recuerda actualizar tu Fork, con el repositorio central. Para hacer esto tienes que tener configurado el remote tal y como se describe en el [paso 2](https://github.com/ofou/fisica#c%C3%B3mo-colaborar) de las instrucciones. Si estás utilizando el IDE ve al menú VCS / Git / Remotes y verifica que esté añadido este repositorio `https://github.com/ofou/fisica` de lo contrario añadelo y luego en el mismo menú ejecuta `fetch` que descarga todos los cambios a tu repo local. Después de eso deberías tener la última versión del repo central. :+1: Cualquier duda estaré atento.

**Comment by FernandoSO** [comment]
Seguí lo recomendado y continua el problema

**Comment by ofou** [comment]
Hola Fernando, puedes adjuntar capturas de tu problema'?

Te recomiendo hacer un `pull `para traer los cambios de la nube al repo local.
