### ISSUE TITLE
cómo se van a dividir las tareas para el proyecto

### ISSUE THREAD

**Issue by hyoga91** [ofou/fisica#36]

**Comment by Xero999** [comment]
es preferible que cada uno vea en lo que tiene mas conocimiento para que sea mas sencillo

**Comment by owllxz** [comment]
@Xero999, durante el fin de semana se van a lanzar todas las tareas a resolver, esta se van a colocar en una especie de lista y se va a dar la opción de que ustedes elija con quien trabajan y que tarea prefieren, en caso de que no se seleccione una tarea durante el plazo estimado, se le asignara un estudiante al azar, al igual que la tarea, Saludos
