### ISSUE TITLE
¿Cómo se hará la distribución de los grupos de trabajo?

### ISSUE THREAD

**Issue by dennis-queirolo** [ofou/fisica#38]

**Comment by owllxz** [comment]
@dennis-queirolo , durante el fin de semana se van a lanzar todas las tareas a resolver, esta se van a colocar en una especie de lista y se va a dar la opción de que ustedes elija con quien trabajan y que tarea prefieren, en caso de que no se seleccione una tarea durante el plazo estimado, se le asignara un estudiante al azar, al igual que la tarea, Saludos

**Comment by ofou** [comment]
duplicate of #36
