### ISSUE TITLE
Gráfica de velocidad

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#40]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by KalegK27** [comment]
Nosotros Matías Pinochet  y Carlos alegría

**Comment by baltiloka** [comment]
lo hare con matias pinochet y carlos alegria

**Comment by ofou** [comment]
@baltiloka, @KalegK27 y @hyoga91 les envié un correo que tienen que aceptar __todos__ para poder asignar la tarea.
Quedo atento a la aceptación. 

Saludos

**Comment by hyoga91** [comment]
Como se hace para subir el archivo?

**Comment by baltiloka** [comment]
di

**Comment by KalegK27** [comment]
hicimos eso pero no funciono daba un error

**Comment by DnLaG** [comment]
> hicimos eso pero no funciono daba un error

qué error? Deben ponerlo acá para poder ayudarles. Suban el log o un pantallazo.

**Comment by ofou** [comment]
Posiblemente no han actualizado el repositorio antes de enviar sus cambios. Recuerden actualizar el repositorio antes de crear su `pull request`
