### ISSUE TITLE
Gráfica de aceleración

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#41]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by Xero999** [comment]
quiero hacer esta Nataniel Muñoz(@Xero999 )con Nicolas Soto (@DracoSt ).

**Comment by ofou** [comment]
Hola @Xero999 y @DracoSt les envié un correo que tienen que aceptar para poder ser asignada la tarea. Saludos quedo atento a la respuesta.

**Comment by Xero999** [comment]
Tambien se nos une Felipe Romero(@C0DAA)

**Comment by Xero999** [comment]
tengo una duda con los datos que ingresan a la función aceleración, ¿que datos o que contiene la expresión self?

**Comment by ofou** [comment]
La expresión `self` contiene todos los elementos que fueron creados en la llamada a la función `init`. Básicamente lo que tienes que centrarte es en extraer los cuatro datos iniciales para graficar tu función.

**Comment by C0DAA** [comment]
wena los cabros
