### ISSUE TITLE
Gráfica de alcance horizontal

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#42]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by ChristianValdiviaP** [comment]
Marcelo Pérez (@ZetZeus)
Christian Valdivia (@ChristianValdiviaP)
