### ISSUE TITLE
Gráfica de altura máxima

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#43]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by FernandoSO** [comment]
Quiero está, Fernando Sangüesa y Bastian Villavicencio

**Comment by ofou** [comment]
Hola @FernandoSO te envié un correo a ti y a @sk8elite una vez que lo acepten aparecerá la tarea asignada.

**Comment by ofou** [comment]
@FernandoSO recuerda que @sk8elite también tiene que aceptar el correo. Si puedes recuérdale.
