### ISSUE TITLE
Gráfica de camino recorrido

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#44]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by dennis-queirolo** [comment]
Cristobal Ruiz, Maro Rivera, Dennis Queirolo. Queremos esta tarea

**Comment by dennis-queirolo** [comment]
@dennis-queirolo 
@maroriv99 
@Ch4Z

**Comment by dennis-queirolo** [comment]
"Incluye documentación de manera concisa y en tono neutral" eso hace referencia a que en nuestra pestaña se encuentren el documento con las ecuaciones o a que hace referencia ??

**Comment by ofou** [comment]
Más bien se refiere a que cuando definan las funciones en `python`, se documente en tono neutral qué es lo que hace cada función y qué argumentos requiere. Si las funciones incluyen ecuaciones tienen que ir documentadas. Ej.

```python
def suma(param1, param2):
    """Esta función toma dos parámetros y devuelve su suma.

    Args:
        param1 (int): El primer número entero
        param2 (int): El segundo número entero

    Returns:
        int: El valor de retorno. Devuelve la suma de los dos parametros"""
    return (param1+param2)
`
