### ISSUE TITLE
Gráfica de radio y centro de curvatura

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#45]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by ofou** [comment]
Chicos @lillo0, @matakuri y @DnLaG ustedes tendrán que hacer esta tarea. 
Por favor acepten el correo para asignarla.

**Comment by DnLaG** [comment]
@lillo0 reportate pls. Tenemos que avanzar

**Comment by DnLaG** [comment]
@ofou La otra vez quedé enredado con lo que tenía que mostrar en esta tarea. Se supone que NO debemos graficar el círculo osculador ya que pertenece a otro grupo de trabajo entonces, qué debo mostrar? Aparte de :

-  "Valor" de la curvatura en una pos determinada
- "Valor" de la curvatura en un tiempo determinado
- Radio (dibujar una línea (Radio)) dentro de la gráfica? -- En base a un tiempo y una pos x.
- Centro de curvatura (Mostrar la pos X,Y del centro de la curvatura? (texto en ventana "pop-up") -- En base a un tiempo y una pos x.

La duda entonces, en resumidas cuentas es, que es lo que debo graficar? Puedo poner los valores en una ventana e imprimirlos, pero de graficar algo, no me queda claro más que graficar/dibujar la línea (radio) de la curvatura.

**Comment by ofou** [comment]
Hola @DnLaG Sólo necesitas el _valor K_ de la curvatura en un _tiempo t_ determinado, y efectivamente tienes que dibujar el **radio** del círculo osculador dentro de la gráfica como una recta perpendicular a la tangente de la función. Por otro lado, el centro de curvatura, imagina el punto central del círculo como se ve en [esta visualización](https://www.ficoumaisfacil.com.br/lazer/arquivos/ciroscul/ciroscul.html).
