### ISSUE TITLE
Gráfica de aceleración normal y tangencial

### ISSUE THREAD

**Issue by ofou** [ofou/fisica#46]
Para realizar la presente tarea es necesario implementar no solo la funcionalidad referente a la descripción del titulo sino también el [diseño](https://github.com/ofou/fisica/raw/master/docs/Presentaci%C3%B3n%20Software%20por%20Prof.%20Hugo%20Iba%C3%B1ez.pdf) y [ecuaciones](https://github.com/ofou/fisica/raw/master/docs/Ecuaciones%20de%20Referencia.pdf) entregadas por el Prof. Hugo Ibáñez.

Checklist de elementos que debe cumplir la presente tarea

- [ ] Incluye `documentación` de manera concisa y en tono neutral
- [ ] Implementa acción de ingresar datos a través del `botón` respectivo
- [ ] Despliega `gráfica` de manera estática utilizando las ecuaciones
- [ ] Muestra `detalles` en el sistema de pares ordenados apropiados al problema
- [ ] Incluye al menos un `test` para su código

**Comment by Siderck** [comment]
Hola nosotros tomamos este ✌️
@MaxiCaceresG 
@LucasVeraa
@Siderck

**Comment by Siderck** [comment]
- [ ] Hacer ventana doble para que el usuario pueda ingresar tiempo o posición
tiempo: [0, tiempo de impacto(formula en pdf)]   // Usuario ingresa un tiempo
posición: [0, alcance horizontal(formula en pdf)] // Usuario ingresa una posición X

- [ ] Hacer gráfico del proyectil

- [ ]  Crear y hacer funcionar las flechas que representan aceleración normal y tangencial

**Comment by ofou** [comment]
Finalmente se decidió ingresar _solo tiempo_ pero si quieren añadir la característica adicional, no haría daño. :wink:  

Saludos

**Comment by Siderck** [comment]
> Finalmente se decidió ingresar _solo tiempo_ pero si quieren añadir la característica adicional, no haría daño. 😉
> 
> Saludos

Ahh ya dale buena, si queda tiempo yo creo que le añadimos eso.

salu2
